### ISSUE TITLE
Unable to access any of the g:localvimrc_ variables.

### ISSUE THREAD

**Issue by symbolix** [embear/vim-localvimrc#35]
Hi,

I am not sure if I am doing something silly, but I am not able to access any of the helper variables:
g:localvimrc_file_dir, g:localvimrc_script_dir etc.

Any ideas?
Thanks

**Comment by embear** [comment]
The variables you mention are just available inside the .lvimrc script file. They can be used to set up your `makeprg` variable for example. They are not available somewhere else because the values of the variables are unambiguous only inside the .lvimrc script file.

I'll add this information to the help file to make the purpose more clear.

**Comment by symbolix** [comment]
Hi,

Thanks for the answer. So I can set and update some global variables through the file, right?

For example:
'let g:my_project_dir=g:localvimrc_script_dir'

But that has to happen in the .localvimr file? Right?

**Comment by embear** [comment]
Yes, this is the correct.
