### ISSUE TITLE
Symlink problem

### ISSUE THREAD

**Issue by humeniuc** [embear/vim-localvimrc#47]
Helloe

My localvimrc in my project is a symlink. 
Because of that, when localvimrc is sourced, g:localvimrc_script and g:localvimrc_script_dir contains the resolved path of the symlink, but I need a way to know the symlink path. I have failed to find that path. Is there a way, other than to hard-code the path in the  localvimrc file?

Thank you

**Comment by embear** [comment]
Hmm, the file is resolved in an very early stage. But it would be easy to have the unresolved file name along with the resolved in an dictionary. I'm currently unsure if the semantic of `g:localvimrc_script` and `g:localvimrc_script_dir` should be changed and it will contain the unresolved name or if there should be a `g:localvimrc_script_unresolved` and `g:localvimrc_script_dir_unresolved` to be backward compatible.
In my opinion changing the semantic of the variables is better because the resolved names are wrong anyway. Any comments?

**Comment by symbolix** [comment]
Please make it backwards compatible as I am sure many people are using this plugin. For me, it is in the core of my project setup scripts and I would be happy if things remain backwards compatible. Thanks.

**Comment by embear** [comment]
Would you mind to test latest commit 2d4c622da0? I added two new variables `g:localvimrc_script_unresolved` and `g:localvimrc_script_dir_unresolved`

**Comment by embear** [comment]
No reply. I suppose it works. Closing issue.

**Comment by humeniuc** [comment]
I just tested, and works perfectly. `g:localvimrc_script_dir_unresolved` did the trick.

Thank you, and I am very sorry for my delayed response. I was travelling for a few weeks and I had not the chance to test the changes.
