### ISSUE TITLE
Working example of using this plugin with ALE?

### ISSUE THREAD

**Issue by msdos** [embear/vim-localvimrc#87]
I can't make this plugin work with ALE to have project specific config.

**Comment by embear** [comment]
This is not a localvimrc problem but a chicken-egg problem. The sequence of events is like this:

1. plugins are loaded (most probable ALE before localvimrc because of the lexical order)
2. buffer for a file in your project is opened and BufEnter event is emitted
3. localvimrc is triggered and loads the settings from `.lvimrc`

By the time the settings are done in the `.lvimrc` file ALE is already initialized and changed settings do not matter. I had a quick look at the documentation of ALE and possibly your are able to restart ALE from your `.lvimrc`. You can try something like this.

First disable ALE by default by adding this to your glocal `.vimrc`

```
" disable ALE globally
let g:ale_disable_lsp=1
```

Second change settings in your `.lvimrc` and start ALE after that

```
if !g:localvimrc_sourced_once
  " add your ALE settings here, for example the following ....
  let g:ale_completion_delay = 1000

  " late start of ALE
  exec "ALEEnable"
endif
```

Another option could be to place ALE as an optional plugin in `~/.vim/pack/ale/opt/ale` so it is not loaded on startup and enable the plugin in your `.lvimrc` after you did the configurations

```
if !g:localvimrc_sourced_once
  " add your ALE settings here, for example the following ....
  let g:ale_completion_delay = 1000

  " late start of ALE
  packadd ale
endif
```

**Comment by msdos** [comment]
To disable ale entirely you need [g:ale_enabled](https://github.com/dense-analysis/ale/blob/c694a241883ec5c33f972a612cfcd464cda3c5fa/doc/ale.txt#L1111)... the variable `g:ale_disable_lsp` disables lsp only.

The problem is: I want to have a default configuration in vimrc, and if there's a local configuration, override. Have tried a mix of these configurations, even adding `let g:localvimrc_event = ['Syntax']` that works with some simple files but somehow it mangles everything with more complex ones (like https://raw.githubusercontent.com/psf/black/main/src/black/brackets.py).

I think I will need to read and understand the source code to try to find a solution... Thanks for the really length explanation.

**Comment by embear** [comment]
Any insights on this issue that could be shared here and might help others? Otherwise I'd close this issue soon.

**Comment by msdos** [comment]
I believe I had a problem with too many moving parts: using pipenv, virtualenv and a bunch of "magic" in a project and restarted over.

In a nutshell: if you're having problems with ALE, if you add in your vimrc:

`let g:localvimrc_event = ['Syntax']`

You can add your ale options or even override some that you already have in vimrc in your . lvimrc. Example: I have `g:ale_linters` in my vimrc, but when I add them in my .lvimrc, they are overriden for linters that are needed for that project only.
